### ISSUE TITLE
Idempotence issues

### ISSUE THREAD

**Issue by kmonticolo** [weareinteractive/ansible-ufw#17]
Hi, this role is not idempotent.

**Comment by kmonticolo** [comment]
to test idempotence in travis you may call latest playbook once again and add "| grep -q 'changed=0.*failed=0' \
    && (echo 'Idempotence test: pass' && exit 0) \
    || (echo 'Idempotence test: fail' && exit 1)" at the end

**Comment by franklinkim** [comment]
Hi, this happens due to the `ufw_reset: yes` option. When enabled you don't need to take care of removing old rules. If you want idempotence, just set it to `no`
