### ISSUE TITLE
Use ansible_port if defined. If not, fallback to port 22

### ISSUE THREAD

**Issue by nununo** [weareinteractive/ansible-ufw#22]
Hello,

Currently port 22 is hard coded:
```
ufw_rules: [{ port: 22, rule: allow }]
```

Whenever the host port is not 22... this variable must be redefined.
I suggest making it more flexible by changing the rule to:
```
ufw_rules: [{ port: '{% if ansible_port is defined %}{{ ansible_port }}{% else %}22{% endif %}', rule: allow }]
```

I'm not sure the jinja2 syntax is correct but the idea is there.

If this is considered a good idea I can implement it a issue a PR.

Thanks!

**Comment by franklinkim** [comment]
Hi,

thanks for the note! 
The role actually expects you to override/define your own `ufw_rules`. 
I kinda just added this one in case you forget to set it and lock yourself out.

Maybe I just should remove it and disable ufw if it's empty...

**Comment by nununo** [comment]
Ah, understood. Makes sense. That's a good option. Closing this then. Thanks!
