### ISSUE TITLE
ERROR! couldn't resolve module/action 'community.general.ufw'

### ISSUE THREAD

**Issue by mf69** [weareinteractive/ansible-ufw#26]
I'm getting this after installing the galaxy role just now.
```
ERROR! couldn't resolve module/action 'community.general.ufw'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/home/mdf/.ansible/roles/weareinteractive.ufw/tasks/service.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Configuring service state
  ^ here
```

My ansible is v2.95 on Ubuntu Focal

**Comment by franklinkim** [comment]
Are you using Ansible >= 2.10 as stated in the README? 
If you're version is lower, use the 1.x releases.

**Comment by mf69** [comment]
As stated in my original message, I am using v2.95.
Is that not >= 2.10?

**Comment by mf69** [comment]
actually I'm wrong it's 2.9.6. I will upgrade my ansible now.
Thanks.

**Comment by ysmaelferradas** [comment]
hola, una consulta encontraste la solucion?

**Comment by ysmaelferradas** [comment]
hello, a query did you find the solution? 
ERROR! couldn't resolve module/action 'community.general.ufw'

**Comment by franklinkim** [comment]
@ysmaelferradas you need to update you ansible version if you want to use the lastest version of this role.

**Comment by kbcz1989** [comment]
Hey guys, what could be a problem on Ansible 2.10?
![image](https://user-images.githubusercontent.com/58665245/108841192-aa450300-75d7-11eb-850c-d68aba92f9f4.png)

**Comment by MihajloManojlovNV** [comment]
`ansible-galaxy collection install community.general`

This was missing. Can this be defined as an explicit dependency?

**Comment by franklinkim** [comment]
@kbcz1989 check your ansible version: ` ansible --version`

**Comment by kbcz1989** [comment]
the actual problem was that community.general collection was not installed:
`ansible-galaxy collection install community.general`

**Comment by cherouvim** [comment]
FWIW installing the `community.general` using:
```
ansible-galaxy collection install community.general
```
was only required on a `ansible 2.9.27` and not on `ansible [core 2.13.7]`.

**Comment by KoltesDigital** [comment]
FTR I had the error. EEs are a new concept to me: it turned out collections are loaded from a Docker container rather from the local filesystem, as it was the case with `ansible-playbook`. For now my workaround is to install collections into _./collections_ ([as documented here](https://ansible.readthedocs.io/projects/navigator/faq/#where-should-ansible-collections-be-placed-when-using-an-execution-environment): `ansible-galaxy collections install community.general -p ./collections`) but I'll probably end up building an EE.
