### ISSUE TITLE
Push 1.5 to ansible galaxy

### ISSUE THREAD

**Issue by pstoll** [weareinteractive/ansible-ufw#4]
Would you be able to get the 1.5 release to https://galaxy.ansible.com/franklinkim/ufw/?

Using the version 1.4, I'm running into the deprecation warnings that it looks like you fixed.

Thanks!

**Comment by franklinkim** [comment]
Sure, imported the new version to galaxy

**Comment by pstoll** [comment]
Much appreciated, thanks.
